
package br.com.caelum.estoque.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstoqueWSImplService", targetNamespace = "http://ws.estoque.caelum.com.br/", wsdlLocation = "http://localhost:8080/estoquews-web/EstoqueWSImpl?wsdl")
public class EstoqueWSImplService
    extends Service
{

    private final static URL ESTOQUEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTOQUEWSIMPLSERVICE_EXCEPTION;
    private final static QName ESTOQUEWSIMPLSERVICE_QNAME = new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/estoquews-web/EstoqueWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTOQUEWSIMPLSERVICE_WSDL_LOCATION = url;
        ESTOQUEWSIMPLSERVICE_EXCEPTION = e;
    }

    public EstoqueWSImplService() {
        super(__getWsdlLocation(), ESTOQUEWSIMPLSERVICE_QNAME);
    }

    public EstoqueWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTOQUEWSIMPLSERVICE_QNAME, features);
    }

    public EstoqueWSImplService(URL wsdlLocation) {
        super(wsdlLocation, ESTOQUEWSIMPLSERVICE_QNAME);
    }

    public EstoqueWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTOQUEWSIMPLSERVICE_QNAME, features);
    }

    public EstoqueWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstoqueWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort() {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTOQUEWSIMPLSERVICE_EXCEPTION!= null) {
            throw ESTOQUEWSIMPLSERVICE_EXCEPTION;
        }
        return ESTOQUEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
